!Jan2011:original code was provided from Astrid from WACCM.
!Aug2011:this code was provided from Fei Wu from the WAM version.
!sep2012: efield.f was separated into each routin for SMS compatibility.
!nm20121012: it looks like this routine is not used!!! (thus not included in Makefile) it is called from the subroutine ROTATE which is also not used. this routine must be related to function get_tilt (weimer96) because it shares the same common block: TRANSDAT.
! 
!--------------------------------------------  
      module module_ROTATEV
!--------------------------------------------------------------------- 
!   L.Scherliess ludger@gaim.cass.usu.edu
! - Weimer96
! Author: A. Maute Dec 2003  am 12/30/03 
!------------------------------------------------------------------------------ 
      implicit none

!nm20121003:module parameters are separated into efield.f!
      public :: ROTATEV

      contains
!-----------------------------------------------------------------------
      SUBROUTINE ROTATEV (A,B,I)       
!         
!-----------------------------------------------------------------------
!     THIS SUBROUTINE APPLIES TO THE VECTOR A(3) THE ITH ROTATION  
!     MATRIX AM(N,M,I) GENERATED BY SUBROUTINE TRANS
!     AND OUTPUTS THE CONVERTED VECTOR B(3), WITH NO CHANGE TO A.
!     IF I IS NEGATIVE, THEN THE INVERSE ROTATION IS APPLIED
!-----------------------------------------------------------------------
!
c     use shr_kind_mod, only: r8 => shr_kind_r8
c     use cam_logfile,  only : iulog
c     use abortutils,   only : endrun

      implicit none 
!
!-------------------------------Commons---------------------------------
!
      real cx, st, ct, am
      COMMON/TRANSDAT/CX(9),ST(6),CT(6),AM(3,3,11)
!
!------------------------------Arguments--------------------------------
!
      integer i
      REAL A(3),B(3)
!
!---------------------------Local variables-----------------------------
!
      integer id, j, iulog
      real xa, ya, za
      iulog=14
!
!-----------------------------------------------------------------------
!
c     IF(I.EQ.0 .OR. IABS(I).GT.11)THEN
c     WRITE(IULOG,*)'ROTATEV CALLED WITH UNDEFINED TRANSFORMATION'
c     CALL ENDRUN
c     ENDIF

      XA = A(1)
      YA = A(2)
      ZA = A(3)
      IF(I.GT.0)THEN
	ID=I
        DO J=1,3
          B(J) = XA*AM(J,1,ID) + YA*AM(J,2,ID) + ZA*AM(J,3,ID)
        ENDDO
      ELSE
	ID=-I
        DO J=1,3
          B(J) = XA*AM(1,J,ID) + YA*AM(2,J,ID) + ZA*AM(3,J,ID)
        ENDDO
      ENDIF
      RETURN        
      END SUBROUTINE ROTATEV
!-----------------------------------------------------------------------
      end module module_ROTATEV
